### ISSUE TITLE
pdfの一覧画面を作る

### ISSUE THREAD

**Issue by nac-39** [NU-wiki-web/nu-wiki-frontend#3]
## 関連Issue, プルリク

- このタスクのためのGitHubのissueとプルリクのリンクを貼る
- 親要件：[[第2回『初回デプロイの要件』『開発ルール』ほか](https://www.notion.so/2-c29d5bf71d734199b49b579684bd3ec8)](https://www.notion.so/2-c29d5bf71d734199b49b579684bd3ec8)

## 要件

- pdfの一覧を取得できる
- pdfの一覧を表示させることができる（`/pdf-list`）

## 設計

- 要件を満たすために何を設計すればいいか？
- ~/components/uiにファイル選択ボタンなどをまとめる
- ~/apiにapiと通信するコードをまとめる
- ~/pages/パス名のフォルダに各ページのコンポーネントを作る

## メモ

- 参考にしたサイトとか、調べたことのメモとか、なんでも

**Comment by yutteee** [comment]
ゆってぃー
- [ ] - [ ] `/file`からファイルの一覧(file_id, name)をバックから取得
- [ ] `/pdf-list`に一覧を表示
ぱうえる
- [ ] pdfの名前をクリック -> idをバックに送って詳細を取得
- [ ] 詳細を表示
