### ISSUE TITLE
openapi.ymlの改修により、pdf-listが壊れた

### ISSUE THREAD

**Issue by nac-39** [NU-wiki-web/nu-wiki-frontend#58]
APIの仕様が若干変わったため、修正する

**Comment by nac-39** [comment]
- フロントでも`openapi.yml`の`schema`のlectureに`exam`を追加する
- APIクライアントの型を生成し直す

**Comment by kentakom1213** [comment]
- [ ] フロントでもopenapi.ymlのschemaのlectureにexamを追加する
- [ ] APIクライアントの型を生成し直す

**Comment by nac-39** [comment]
メモ：

左側： `/lectures/search` or `/lecture-list`
右側： `/pdf-list/:id`

![スクリーンショット 2023-10-22 22 36 37](https://github.com/NU-wiki-web/nu-wiki-frontend/assets/83295760/4b18e2d5-7971-48c7-ab06-59a362183aa2)

**Comment by kentakom1213** [comment]
復旧（講義情報はAPIが壊れていたため戻せず）

![image](https://github.com/NU-wiki-web/nu-wiki-frontend/assets/64479799/839f6542-1e07-44f7-afb1-9a92a6b2f49e)

**Comment by nac-39** [comment]
このプルリクで完了： https://github.com/NU-wiki-web/nu-wiki-frontend/pull/82
